Repository inisis/OnnxSlim, pull requests merged in 2025-06, with the labels that each got.

#124 fix: super large model check error
  onnxslim/utils.py
Labels: bug

#128 Update setup.py
  setup.py
Labels: enhancement

#129 Update README.md
  README.md
Labels: documentation
